// Generated by CoffeeScript 1.8.0
(function() {
  var Resource;

  Resource = require('./lib/resource-manager');

  exports.ResourceType = Resource.ResourceType;

  exports.ResourceOptions = Resource.ResourceOptions;

  exports.ResourceManager = Resource.ResourceManager;

}).call(this);

//# sourceMappingURL=index.js.map
